apiVersion: apps/v1
kind: Deployment
metadata:
  name: fixtures-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fixtures
  template:
    metadata:
      labels:
        app: fixtures
    spec:
      containers:
        - name: fixtures
          image: alonmyburgh/fixtures
          env:
            - name: MONGO_URI
              value: 'mongodb://fixtures-mongo-srv:27017/fixtures'
            - name: NODE_ENV
              value: 'production'
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: API_KEY
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_URL
              value: fixtures-redis-srv
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: sportlive
---
apiVersion: v1
kind: Service
metadata:
  name: fixtures-srv
spec:
  selector:
    app: fixtures
  ports:
    - name: fixtures
      protocol: TCP
      port: 3001
      targetPort: 3001
